name = "AnalytIntegralD0"
uuid = "49d4d070-7366-40d9-8484-291b68b4f7aa"
authors = ["PeilinZhang"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
